export const TermsContent = () => {
  return (
    <div className="space-y-6 text-gray-700">
      <div className="prose prose-lg max-w-none">
        <h3 className="text-2xl font-bold text-gray-800 mb-6">Flames Check – Terms of Use</h3>
        
        <div className="bg-yellow-50 border border-yellow-200 rounded-xl p-6 mb-6">
          <p className="text-yellow-800 font-semibold">
            📅 Last Updated: October 28, 2025
          </p>
        </div>

        <div className="space-y-6">
          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">Welcome to FlamesCheck.com</h4>
            <p className="text-gray-600 leading-relaxed">
              Welcome to FlamesCheck.com — the modern revival of the viral 90s FLAMES love game!
              These Terms of Use explain how you can use our website, features, and content.
              By accessing or using Flames Check, you agree to these Terms and our Privacy Policy.
              If you don't agree, please don't use the site.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">1️⃣ Overview</h4>
            <p className="text-gray-600 leading-relaxed">
              FlamesCheck.com ("we," "us," or "our") provides an entertainment-based online love compatibility and vibe-check experience.
              Our goal is to make relationships fun, lighthearted, and social — not to give professional advice or guaranteed results.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">2️⃣ Eligibility</h4>
            <p className="text-gray-600 leading-relaxed">
              You must be at least 13 years old to use Flames Check.
              If you're under 18, please ask a parent or guardian before using the site.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">3️⃣ Entertainment-Only Disclaimer</h4>
            <p className="text-gray-600 leading-relaxed">
              Flames Check is for entertainment purposes only.
              Results generated by our calculator or features (including "Celebrity Flames Check") are not scientific or factual relationship assessments.
              Do not rely on them for emotional, financial, or personal decisions.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">4️⃣ Your Use of the Site</h4>
            <p className="text-gray-600 leading-relaxed mb-3">You agree to:</p>
            <ul className="list-disc list-inside text-gray-600 space-y-1 ml-4">
              <li>Use Flames Check responsibly and respectfully</li>
              <li>Not attempt to hack, copy, or misuse our code or content</li>
              <li>Not post or share content that is hateful, harmful, or illegal</li>
              <li>Use the service only for personal, non-commercial purposes</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-3">
              We reserve the right to suspend access for users who violate these terms.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">5️⃣ Intellectual Property</h4>
            <p className="text-gray-600 leading-relaxed">
              All content on FlamesCheck.com — including text, design, branding, graphics, and algorithms — is owned or licensed by us and protected by copyright laws.
              You may share results or screenshots for personal or social media use, but please credit FlamesCheck.com.
              You may not copy, distribute, or sell any part of our website without written permission.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">6️⃣ Privacy</h4>
            <p className="text-gray-600 leading-relaxed">
              We respect your privacy.
              Flames Check does not store names, results, or personal data entered in the calculator.
              For full details, please read our Privacy Policy.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">7️⃣ Limitation of Liability</h4>
            <p className="text-gray-600 leading-relaxed mb-3">By using FlamesCheck.com, you agree that we are not liable for:</p>
            <ul className="list-disc list-inside text-gray-600 space-y-1 ml-4">
              <li>Any emotional or social outcomes from using the site</li>
              <li>Any damages, losses, or misunderstandings from the results provided</li>
              <li>Any temporary downtime or technical errors</li>
            </ul>
            <p className="text-gray-600 leading-relaxed mt-3">
              You use the site at your own discretion.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">8️⃣ Third-Party Links</h4>
            <p className="text-gray-600 leading-relaxed">
              Flames Check may include links to social media or partner websites.
              We are not responsible for content or privacy practices on third-party sites.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">9️⃣ Updates to Terms</h4>
            <p className="text-gray-600 leading-relaxed">
              We may update these Terms occasionally to reflect new features or laws.
              Any changes will be posted here with the updated "Last Updated" date.
              Your continued use means you accept the updated Terms.
            </p>
          </div>

          <div className="bg-white border border-gray-200 rounded-xl p-6">
            <h4 className="text-lg font-semibold text-gray-800 mb-3">🔟 Contact Us</h4>
            <p className="text-gray-600 leading-relaxed">
              Got questions or feedback?
              Reach us anytime at:
            </p>
            <p className="text-lg font-semibold text-blue-600 mt-2">
              📧 flamescheck2025@gmail.com
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};
